[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.22.1"
tag_format = "v$version"
version_files = [
    ".cz.toml:version",
    "versioning/version.go:Version",
]
bump_message = "bump: Semantic Release Bot: Realease Version: $new_version 🤖🚀 [skip ci]"
