# https://taskfile.dev

version: '3'

tasks:
  test:
    desc: Run test with ginkgo
    cmds:
      - go tool ginkgo run -v ./...

  integration_test:
    desc: Run project integration test
    cmds:
      - ./scripts/run_integration_test.sh

  install:
    deps: [generate]
    cmds:
      - go install

  fmt:
    desc: Format all code
    cmds:
      - go fmt ./...

  version:
    desc: Current version of gomancer
    cmds:
      - cz version -p

  generate:
    desc: Generates all needed code for project
    cmds:
      - go tool templ generate --proxy="http://localhost:8090" --open-browser=false -v
