# https://taskfile.dev

version: '3'

tasks:
  test:
    desc: Run test with ginkgo
    cmds:
      - ginkgo run -v ./...
      - ./scripts/run_integration_test.sh

  install:
    cmds:
      - go install

  fmt:
    desc: Format all code
    cmds:
      - go fmt ./...

  version:
    desc: Current version of gomancer
    cmds:
      - cz version -p
