package gormimpl

import (
	"fmt"
	. "github.com/dave/jennifer/jen"
	"github.com/manicar2093/gomancer/domain"
	"github.com/rjNemo/underscore"
	"path"
)

type (
	generatorData struct {
		repositoryStructName string
		dbKey                string
		receiverStatement    Code
		receiverVar          string
	}
	generatorType func(domain.GenerateModelInput, generatorData) Code
)

func GenerateRepository(input domain.GenerateModelInput) error {
	repositoryStructName := fmt.Sprintf("%sRepository", input.PascalCase)
	receiverVar := "c"
	data := generatorData{
		repositoryStructName: repositoryStructName,
		dbKey:                "db",
		receiverStatement:    Id(receiverVar).Op("*").Add(Id(repositoryStructName)),
		receiverVar:          receiverVar,
	}
	f := NewFile(input.SnakeCase)
	f.PackageComment("// Code generated by gomancer")

	generators := []generatorType{
		generateRepoStruct,
		generateRepoConstructor,
		generateSaveMethod,
		generateGetByIdMethod,
		generatedGetAllPaginatedMethod,
		generatePartialUpdateFunction,
		generateDeleteByIdFunction,
	}

	underscore.Each(generators, func(generator generatorType) {
		f.Add(generator(input, data))
	})

	return f.Save(
		path.Join(
			string(domain.InternalPackagePath),
			input.SnakeCase,
			"repository_gomancer.go",
		),
	)
}

func generateRepoStruct(input domain.GenerateModelInput, generatorData generatorData) Code {
	return Type().Id(generatorData.repositoryStructName).Struct(
		Id(generatorData.dbKey).Op("*").Qual(domain.WinterConnPkgPath, "ConnWrapper"),
	).Line().Line()
}

func generateRepoConstructor(input domain.GenerateModelInput, generatorData generatorData) Code {
	return Func().Id(fmt.Sprintf("New%sRepository", input.PascalCase)).Params(
		Id(generatorData.dbKey).Op("*").Qual(domain.WinterConnPkgPath, "ConnWrapper"),
	).Op("*").Id(generatorData.repositoryStructName).Block(
		Return(
			Op("&").Id(generatorData.repositoryStructName).Values(
				Dict{
					Id(generatorData.dbKey): Id(generatorData.dbKey),
				},
			),
		),
	).Line().Line()
}

func generateSaveMethod(input domain.GenerateModelInput, generatorData generatorData) Code {
	return Comment("// Save can Create and Update an entity. You can use this for http PATH method. Check https://gorm.io/docs/update.html#Save-All-Fields for more info").
		Line().
		Func().Params(generatorData.receiverStatement).Id("Save").Params(
		Id("input").Op("*").Add(
			domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase)),
	).Error().Block(
		If(
			Id("res").Op(":=").Id(generatorData.receiverVar).Dot(generatorData.dbKey).Dot("Save").Call(
				Id("input"),
			),
			Id("res").Dot("Error").Op("!=").Nil(),
		).Block(
			Return(Id("res").Dot("Error")),
		),
		Return(Nil()),
	).Line().Line()
}

func generateGetByIdMethod(input domain.GenerateModelInput, generatorData generatorData) Code {
	return Func().Params(generatorData.receiverStatement).Id("GetById").Params(
		Id("id").Add(domain.QualifiersByType(input.IdAttribute.Type)),
	).Params(
		Op("*").Add(domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase)),
		Error(),
	).Block(
		Var().Id("found").Add(domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase)),
		If(
			Id("res").Op(":=").Id(generatorData.receiverVar).Dot(generatorData.dbKey).Dot("First").Call(
				Op("&").Id("found"),
				Id("id"),
			),
			Id("res").Dot("Error").Op("!=").Nil(),
		).Block(
			Return(Nil(), Id("res").Dot("Error")),
		),
		Return(Op("&").Id("found"), Nil()),
	).Line().Line()
}

func generatedGetAllPaginatedMethod(input domain.GenerateModelInput, generatorData generatorData) Code {
	return Func().Params(generatorData.receiverStatement).Id("GetAllPaginated").Params(
		Id("pageNumber").Op(",").Id("pageSize").Int(),
	).Params(
		Op("*").Qual(domain.GormPagerPkgPath, "Page").Index(domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase)),
		Error(),
	).Block(
		Id("pager").Op(":=").Qual(domain.GormPagerPkgPath, "Page").Index(domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase)).Values(
			Id("PageSize").Op(":").Int64().Call(Id("pageSize")),
			Id("CurrentPage").Op(":").Int64().Call(Id("pageNumber")),
		),
		If(
			Id("err").Op(":=").Id("pager").Dot("SelectPages").Call(
				Id(generatorData.receiverVar).Dot(generatorData.dbKey).Dot("GormPager"),
				Id(generatorData.receiverVar).Dot(generatorData.dbKey).Dot("DB"),
			),
			Id("err").Op("!=").Nil(),
		).Block(
			Return(Nil(), Err()),
		),
		Return(Op("&").Id("pager"), Nil()),
	).Line().Line()
}

func generatePartialUpdateFunction(input domain.GenerateModelInput, generatorData generatorData) Code {
	return Type().
		Id("PartialUpdateByIdInput").
		StructFunc(func(g *Group) {
			g.
				Id(input.IdAttribute.PascalCase).
				Add(domain.QualifiersByType(input.IdAttribute.Type)).
				Tag(
					domain.Tags(
						input.IdAttribute,
						domain.Validations{Required: true},
						domain.JsonTag, domain.ParamTag,
					),
				)
			underscore.Map(input.Attributes, func(item domain.Attribute) Code {
				return g.Id(item.PascalCase).Qual(domain.GoptionPkgPath, "Optional").Index(
					domain.QualifiersByType(item.Type),
				).Tag(domain.Tags(item, domain.Validations{}, domain.JsonTag))
			})
		}).
		Line().
		Line().
		Comment("PartialUpdateById can select which field has to be updated from given input").
		Line().
		Func().
		Params(generatorData.receiverStatement).
		Id("PartialUpdateById").
		Params(
			Id("changes").Id("PartialUpdateByIdInput"),
		).
		Params(
			Op("*").Add(domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase)),
			Error(),
		).BlockFunc(
		func(g *Group) {
			g.Var().
				Defs(
					Id("result").
						Op("=").
						Add(
							domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase),
						).
						Values(),
					Id("updates").
						Op("=").
						Map(String()).
						Any().
						Values(),
				).
				Line()

			underscore.Each(input.Attributes, func(attribute domain.Attribute) {
				g.If(
					Id("changes").
						Dot(attribute.PascalCase).
						Dot("IsPresent").
						Call(),
				).Block(
					Id("updates").
						Index(Lit(attribute.SnakeCase)).
						Op("=").
						Id("changes").
						Dot(attribute.PascalCase).
						Dot("MustGet").
						Call(),
				)
			})

			g.
				Line().
				Line().
				If(
					Id("res").
						Op(":=").
						Id(generatorData.receiverVar).
						Dot(generatorData.dbKey).
						Dot("Model").
						Call(Op("&").Id("result")).
						Dot("Clauses").
						Call(Id("clause.Returning{}")).
						Dot("Where").
						Call(Lit("id = ?"), Id("changes").Dot("Id")).
						Dot("Updates").
						Call(Id("updates")),
					Id("res").Dot("Error").Op("!=").Nil(),
				).
				Block(
					Return(Nil(), Id("res").Dot("Error")),
				).
				Line().
				Line().
				Return(
					Op("&").Id("result"),
					Nil(),
				)
		},
	).
		Line().
		Line()

}

func generateDeleteByIdFunction(input domain.GenerateModelInput, generatorData generatorData) Code {
	return Func().
		Params(generatorData.receiverStatement).
		Id("DeleteById").
		Params(
			Id("id").
				Add(domain.QualifiersByType(input.IdAttribute.Type)),
		).
		Error().
		Block(
			If(
				Id("res").
					Op(":=").
					Id(generatorData.receiverVar).
					Dot(generatorData.dbKey).
					Dot("Delete").
					Call(
						Op("&").
							Add(domain.GetPackageQualifier(input.ModuleInfo.Name, domain.InternalDomainModelsPackagePath, input.PascalCase)).
							Values(),
						Lit("id = ?"),
						Id("id"),
					),
				Id("res").
					Dot("Error").
					Op("!=").
					Nil(),
			).Block(
				Return(
					Id("res").Dot("Error"),
				),
			),
			Return(Nil()),
		)
}
