package gormimpl

import (
	"fmt"
	"github.com/charmbracelet/log"
	. "github.com/dave/jennifer/jen"
	"github.com/jinzhu/inflection"
	"github.com/manicar2093/gomancer/deps"
	"github.com/manicar2093/gomancer/domain"
	"github.com/manicar2093/gomancer/parser"
	"github.com/manicar2093/gomancer/tags"
	"github.com/manicar2093/gomancer/types"
	"github.com/rjNemo/underscore"
	"os"
	"path"
)

type (
	generatorData struct {
		repositoryStructName string
		db                   string
		receiverStatement    Code
		receiverVar          string
		modelQualifier       Code
	}
	generatorType func(parser.GenerateModelInput, generatorData, deps.Container) Code
)

func GenerateRepository(input parser.GenerateModelInput, goDeps deps.Container) error {
	log.Info("Generating gorm repository...")
	repositoryStructName := fmt.Sprintf("%sRepository", input.PascalCase)
	receiverVar := "c"
	data := generatorData{
		repositoryStructName: repositoryStructName,
		db:                   "db",
		receiverStatement:    Id(receiverVar).Op("*").Add(Id(repositoryStructName)),
		receiverVar:          receiverVar,
		modelQualifier:       Qual(goDeps.Internal.Models.Path, input.PascalCase),
	}
	f := NewFile(inflection.Plural(input.LowerNoSpaceCase))
	f.PackageComment("// Code generated by gomancer")

	generators := []generatorType{
		generateRepoStruct,
		generateRepoConstructor,
		generateSaveMethod,
		generateGetByIdMethod,
		generatedGetAllPaginatedMethod,
		generatePartialUpdateFunction,
		generateDeleteByIdFunction,
	}

	underscore.Each(generators, func(generator generatorType) {
		f.Add(generator(input, data, goDeps))
	})

	modelPackagePath := path.Join(
		string(domain.InternalPackagePath),
		input.PackageEntityName,
	)
	if err := os.MkdirAll(modelPackagePath, os.ModePerm); err != nil {
		return err
	}

	return f.Save(
		path.Join(
			modelPackagePath,
			"repository_gomancer.go",
		),
	)
}

func generateRepoStruct(input parser.GenerateModelInput, generatorData generatorData, goDeps deps.Container) Code {
	return Type().Id(generatorData.repositoryStructName).Struct(
		Id(generatorData.db).Op("*").Qual(goDeps.Project.Core.Connections.Path, "ConnWrapper"),
	).Line().Line()
}

func generateRepoConstructor(input parser.GenerateModelInput, generatorData generatorData, goDeps deps.Container) Code {
	return Func().Id(fmt.Sprintf("New%sRepository", input.PascalCase)).Params(
		Id(generatorData.db).Op("*").Qual(goDeps.Project.Core.Connections.Path, "ConnWrapper"),
	).Op("*").Id(generatorData.repositoryStructName).Block(
		Return(
			Op("&").Id(generatorData.repositoryStructName).Values(
				Dict{
					Id(generatorData.db): Id(generatorData.db),
				},
			),
		),
	).Line().Line()
}

func generateSaveMethod(input parser.GenerateModelInput, generatorData generatorData, _ deps.Container) Code {
	return Comment("// Save can Create and Update an entity. You can use this for http PATH method. Check https://gorm.io/docs/update.html#Save-All-Fields for more info").
		Line().
		Func().Params(generatorData.receiverStatement).Id("Save").Params(
		Id("input").Op("*").Add(
			generatorData.modelQualifier),
	).Error().Block(
		If(
			Id("res").Op(":=").Id(generatorData.receiverVar).Dot(generatorData.db).Dot("Save").Call(
				Id("input"),
			),
			Id("res").Dot("Error").Op("!=").Nil(),
		).Block(
			Return(Id("res").Dot("Error")),
		),
		Return(Nil()),
	).Line().Line()
}

func generateGetByIdMethod(input parser.GenerateModelInput, generatorData generatorData, goDeps deps.Container) Code {
	return Func().Params(generatorData.receiverStatement).Id("GetById").Params(
		Id("id").Add(types.QualifiersByType(input.IdAttribute.Type, goDeps, input.IdAttribute.PascalCase, false)),
	).Params(
		Op("*").Add(generatorData.modelQualifier),
		Error(),
	).Block(
		Var().Id("found").Add(generatorData.modelQualifier),
		If(
			Id("res").Op(":=").Id(generatorData.receiverVar).Dot(generatorData.db).Dot("First").Call(
				Op("&").Id("found"),
				Id("id"),
			),
			Id("res").Dot("Error").Op("!=").Nil(),
		).Block(
			Return(Nil(), Id("res").Dot("Error")),
		),
		Return(Op("&").Id("found"), Nil()),
	).Line().Line()
}

func generatedGetAllPaginatedMethod(input parser.GenerateModelInput, generatorData generatorData, goDeps deps.Container) Code {
	return Func().Params(generatorData.receiverStatement).Id("GetAllPaginated").Params(
		Id("pageNumber").Op(",").Id("pageSize").Int(),
	).Params(
		Op("*").Qual(goDeps.GormPager.Path, "Page").Index(generatorData.modelQualifier),
		Error(),
	).Block(
		Id("pager").Op(":=").Qual(goDeps.GormPager.Path, "Page").Index(generatorData.modelQualifier).Values(
			Id("PageSize").Op(":").Int64().Call(Id("pageSize")),
			Id("CurrentPage").Op(":").Int64().Call(Id("pageNumber")),
		),
		If(
			Id("err").Op(":=").Id("pager").Dot("SelectPages").Call(
				Id(generatorData.receiverVar).Dot(generatorData.db).Dot("GormPager"),
				Id(generatorData.receiverVar).Dot(generatorData.db).Dot("DB"),
			),
			Id("err").Op("!=").Nil(),
		).Block(
			Return(Nil(), Err()),
		),
		Return(Op("&").Id("pager"), Nil()),
	).Line().Line()
}

func generatePartialUpdateFunction(input parser.GenerateModelInput, generatorData generatorData, goDeps deps.Container) Code {
	return Type().
		Id("PartialUpdateByIdInput").
		StructFunc(func(g *Group) {
			g.
				Id(input.IdAttribute.PascalCase).
				Add(types.QualifiersByType(input.IdAttribute.Type, goDeps, input.IdAttribute.PascalCase, true)).
				Tag(
					tags.Tags(
						tags.NewJson(tags.JsonOptions{
							Name: input.IdAttribute.SnakeCase,
						}),
						tags.NewEcho(tags.EchoOptions{
							Name: input.IdAttribute.SnakeCase,
							Tag:  tags.EchoParam,
						}),
						tags.NewValidate(
							underscore.Ternary[tags.ValidateGenerable](
								input.IdAttribute.Type == string(types.TypeUuid),
								tags.ValidateRequiredUuid{},
								tags.ValidateRequired{},
							),
						),
					),
				)
			underscore.Map(input.Attributes, func(item parser.Attribute) Code {
				return g.Id(item.PascalCase).Qual(domain.GoptionPkgPath, "Optional").Index(
					types.QualifiersByType(item.Type, goDeps, item.PascalCase, true),
				).Tag(
					tags.Tags(
						tags.NewJson(
							tags.JsonOptions{
								Name: item.SnakeCase,
							},
						),
					),
				)
			})
		}).
		Line().
		Line().
		Comment("PartialUpdateById can select which field has to be updated from given input").
		Line().
		Func().
		Params(generatorData.receiverStatement).
		Id("PartialUpdateById").
		Params(
			Id("changes").Id("PartialUpdateByIdInput"),
		).
		Params(
			Op("*").Add(generatorData.modelQualifier),
			Error(),
		).BlockFunc(
		func(g *Group) {
			g.Var().
				Defs(
					Id("result").
						Op("=").
						Add(
							generatorData.modelQualifier,
						).
						Values(),
					Id("updates").
						Op("=").
						Map(String()).
						Any().
						Values(),
				).
				Line()

			underscore.Each(input.Attributes, func(attribute parser.Attribute) {
				g.If(
					Id("changes").
						Dot(attribute.PascalCase).
						Dot("IsPresent").
						Call(),
				).Block(
					Id("updates").
						Index(Lit(attribute.SnakeCase)).
						Op("=").
						Id("changes").
						Dot(attribute.PascalCase).
						Dot("MustGet").
						Call(),
				)
			})

			g.
				Line().
				If(
					Id("len").
						Call(
							Qual("slices", "Collect").
								Call(
									Qual("maps", "Keys").
										Call(
											Id("updates"),
										),
								),
						).
						Op("==").
						Lit(0),
				).Block(
				If(
					Id("res").
						Op(":=").
						Id(generatorData.receiverVar).
						Dot(generatorData.db).
						Dot("First").
						Call(
							Op("&").Id("result"),
							Id("changes").Dot("Id"),
						),
					Id("res").
						Dot("Error").
						Op("!=").
						Nil(),
				).Block(
					Return(Nil(), Id("res").Dot("Error")),
				),

				Return(Id("&result"), Nil()),
			)

			g.
				Line().
				Line().
				If(
					Id("res").
						Op(":=").
						Id(generatorData.receiverVar).
						Dot(generatorData.db).
						Dot("Model").
						Call(Op("&").Id("result")).
						Dot("Clauses").
						Call(Qual(goDeps.Gorm.Clause.Path, "Returning").Values()).
						Dot("Where").
						Call(Lit("id = ?"), Id("changes").Dot("Id")).
						Dot("Updates").
						Call(Id("updates")),
					Id("res").Dot("Error").Op("!=").Nil(),
				).
				Block(
					Return(Nil(), Id("res").Dot("Error")),
				).
				Line().
				Line().
				Return(
					Op("&").Id("result"),
					Nil(),
				)
		},
	).
		Line().
		Line()

}

func generateDeleteByIdFunction(input parser.GenerateModelInput, generatorData generatorData, goDeps deps.Container) Code {
	return Func().
		Params(generatorData.receiverStatement).
		Id("DeleteById").
		Params(
			Id("id").
				Add(types.QualifiersByType(input.IdAttribute.Type, goDeps, input.IdAttribute.PascalCase, false)),
		).
		Error().
		Block(
			If(
				Id("res").
					Op(":=").
					Id(generatorData.receiverVar).
					Dot(generatorData.db).
					Dot("Delete").
					Call(
						Op("&").
							Add(generatorData.modelQualifier).
							Values(),
						Lit("id = ?"),
						Id("id"),
					),
				Id("res").
					Dot("Error").
					Op("!=").
					Nil(),
			).Block(
				Return(
					Id("res").Dot("Error"),
				),
			),
			Return(Nil()),
		)
}
