{{define "Makefile"}}# Run templ generation in watch mode
templ:
{{"\t"}}go tool templ generate --watch --proxy="http://localhost:8090" --open-browser=false -v

# Watch Tailwind CSS changes
tailwind:
{{"\t"}}tailwindcss -i ./cmd/service/sources/css/input.css -o ./cmd/service/assets/css/styles.css --watch

# Start development server with all watchers
dev:
{{"\t"}}go tool air
{{end}}